#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/Users/tomasrezac/Documents/dev/zero-music/node_modules/.pnpm/@rocicorp+zero-sqlite3@1.1.2/node_modules/@rocicorp/zero-sqlite3/node_modules:/Users/tomasrezac/Documents/dev/zero-music/node_modules/.pnpm/@rocicorp+zero-sqlite3@1.1.2/node_modules/@rocicorp/node_modules:/Users/tomasrezac/Documents/dev/zero-music/node_modules/.pnpm/@rocicorp+zero-sqlite3@1.1.2/node_modules:/Users/tomasrezac/Documents/dev/zero-music/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/Users/tomasrezac/Documents/dev/zero-music/node_modules/.pnpm/@rocicorp+zero-sqlite3@1.1.2/node_modules/@rocicorp/zero-sqlite3/node_modules:/Users/tomasrezac/Documents/dev/zero-music/node_modules/.pnpm/@rocicorp+zero-sqlite3@1.1.2/node_modules/@rocicorp/node_modules:/Users/tomasrezac/Documents/dev/zero-music/node_modules/.pnpm/@rocicorp+zero-sqlite3@1.1.2/node_modules:/Users/tomasrezac/Documents/dev/zero-music/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../shell.js" "$@"
else
  exec node  "$basedir/../../shell.js" "$@"
fi
