import * as React from "react";
import type { Decorator, Preview } from "@storybook/react-vite";

// Design-token CSS variables and fonts. Importing the app stylesheet keeps
// Storybook in sync with the real app. (Reset, utilities and keyframes come
// from the Panda stylesheet imported below.)
// oxlint-disable-next-line no-unassigned-import -- CSS side-effect import
import "../../../apps/zero-app/src/styles.css";
// Panda CSS — prebuilt stylesheet generated by `panda cssgen` (deno task panda).
// oxlint-disable-next-line no-unassigned-import -- CSS side-effect import
import "@zero-app/styled-system/styles.css";

const withTheme: Decorator = (Story, context) => {
  const theme = context.globals.theme ?? "light";
  React.useEffect(() => {
    const root = document.documentElement;
    root.classList.toggle("dark", theme === "dark");
    root.style.colorScheme = theme;
  }, [theme]);
  return (
    <div>
      <Story />
    </div>
  );
};

const preview: Preview = {
  parameters: {
    layout: "centered",
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
    a11y: { test: "todo" },
  },
  globalTypes: {
    theme: {
      description: "Color theme",
      defaultValue: "light",
      toolbar: {
        title: "Theme",
        icon: "circlehollow",
        items: [
          { value: "light", title: "Light", icon: "sun" },
          { value: "dark", title: "Dark", icon: "moon" },
        ],
        dynamicTitle: true,
      },
    },
  },
  decorators: [withTheme],
};

export default preview;
