// Panda CSS config - no @pandacss/dev import to avoid esbuild bundling issues
/** @type {import('@pandacss/dev').Config} */
export default {
  preflight: true,

  include: ["./libs/**/*.{ts,tsx}", "./apps/**/*.{ts,tsx}"],
  exclude: ["**/node_modules/**", "**/*.stories.*"],

  outdir: "styled-system",
  jsxFramework: "react",

  conditions: {
    extend: {
      dark: ".dark &",
      groupButton: ".group\\/button &",
      groupCard: ".group\\/card &",
      groupCardHeader: ".group\\/card-header &",
      groupBadge: ".group\\/badge &",
      groupAlert: ".group\\/alert &",
      groupTabs: ".group\\/tabs &",
      groupTabsList: ".group\\/tabs-list &",
      groupAccordionTrigger: ".group\\/accordion-trigger &",
      groupAvatar: ".group\\/avatar &",
      groupAvatarGroup: ".group\\/avatar-group &",
      groupFieldGroup: ".group\\/field-group &",
      groupField: ".group\\/field &",
      groupSwitch: ".group\\/switch &",
      groupSidebar: ".group\\/sidebar &",
      groupSidebarWrapper: ".group\\/sidebar-wrapper &",
      groupToggle: ".group\\/toggle &",
      groupSidebarMenu: ".group\\/sidebar-menu &",
      ariaInvalid: "&[aria-invalid='true']",
      ariaExpanded: "&[aria-expanded='true']",
      ariaPressed: "&[aria-pressed='true']",
      ariaDisabled: "&[aria-disabled='true']",
      ariaSelected: "&[aria-selected='true']",
      ariaHaspopup: "&[aria-haspopup]",
      dataActive: "&[data-active]",
      dataOpen: "&[data-open]",
      dataClosed: "&[data-closed]",
      dataChecked: "&[data-checked]",
      dataUnchecked: "&[data-unchecked]",
      dataDisabled: "&[data-disabled]",
      dataStartingStyle: "&[data-starting-style]",
      dataEndingStyle: "&[data-ending-style]",
      dataHorizontal: "&[data-orientation='horizontal']",
      dataVertical: "&[data-orientation='vertical']",
      dataSizeDefault: "&[data-size='default']",
      dataSizeSm: "&[data-size='sm']",
      dataSizeLg: "&[data-size='lg']",
      dataVariantLine: "&[data-variant='line']",
      dataSidebarExpanded: "&[data-state='expanded']",
      dataSidebarCollapsed: "&[data-state='collapsed']",
      peerDisabled: ".peer:disabled ~ &, .peer[disabled] ~ &",
    },
  },

  theme: {
    extend: {
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--accordion-panel-height)" },
        },
        "accordion-up": {
          from: { height: "var(--accordion-panel-height)" },
          to: { height: "0" },
        },
        spin: {
          to: { transform: "rotate(360deg)" },
        },
        pulse: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: ".5" },
        },
      },
      tokens: {
        fonts: {
          sans: {
            value: "'Oxanium Variable', ui-sans-serif, system-ui, sans-serif",
          },
        },
        radii: {
          sm: { value: "calc(var(--radius) - 4px)" },
          md: { value: "calc(var(--radius) - 2px)" },
          lg: { value: "var(--radius)" },
          xl: { value: "calc(var(--radius) + 4px)" },
          "2xl": { value: "1rem" },
          "3xl": { value: "1.5rem" },
          "4xl": { value: "2rem" },
          full: { value: "9999px" },
        },
        animations: {
          "accordion-down": { value: "accordion-down 0.2s ease-out" },
          "accordion-up": { value: "accordion-up 0.2s ease-in" },
          spin: { value: "spin 1s linear infinite" },
          pulse: { value: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite" },
        },
      },
      semanticTokens: {
        colors: {
          background: { value: "var(--background)" },
          foreground: { value: "var(--foreground)" },
          card: { value: "var(--card)" },
          "card-foreground": { value: "var(--card-foreground)" },
          popover: { value: "var(--popover)" },
          "popover-foreground": { value: "var(--popover-foreground)" },
          primary: { value: "var(--primary)" },
          "primary-foreground": { value: "var(--primary-foreground)" },
          secondary: { value: "var(--secondary)" },
          "secondary-foreground": { value: "var(--secondary-foreground)" },
          muted: { value: "var(--muted)" },
          "muted-foreground": { value: "var(--muted-foreground)" },
          accent: { value: "var(--accent)" },
          "accent-foreground": { value: "var(--accent-foreground)" },
          destructive: { value: "var(--destructive)" },
          border: { value: "var(--border)" },
          input: { value: "var(--input)" },
          ring: { value: "var(--ring)" },
          "chart-1": { value: "var(--chart-1)" },
          "chart-2": { value: "var(--chart-2)" },
          "chart-3": { value: "var(--chart-3)" },
          "chart-4": { value: "var(--chart-4)" },
          "chart-5": { value: "var(--chart-5)" },
          sidebar: { value: "var(--sidebar)" },
          "sidebar-foreground": { value: "var(--sidebar-foreground)" },
          "sidebar-primary": { value: "var(--sidebar-primary)" },
          "sidebar-primary-foreground": {
            value: "var(--sidebar-primary-foreground)",
          },
          "sidebar-accent": { value: "var(--sidebar-accent)" },
          "sidebar-accent-foreground": {
            value: "var(--sidebar-accent-foreground)",
          },
          "sidebar-border": { value: "var(--sidebar-border)" },
          "sidebar-ring": { value: "var(--sidebar-ring)" },
        },
      },
    },
  },
};
