#!/usr/bin/env node
//#region src/build-schema.ts
console.warn("zero-build-schema is deprecated.\n");
console.info("Run `npx zero-deploy-permissions` to deploy permissions.\n");
process.exit(-1);
//#endregion
export {};

//# sourceMappingURL=build-schema.js.map