import { defineSlotRecipe } from "./define-recipe";

export const avatarRecipe = defineSlotRecipe({
  className: "avatar",
  slots: ["root", "image", "fallback", "badge", "group", "groupCount"],
  base: {
    root: {
      position: "relative",
      display: "flex",
      size: "8",
      flexShrink: "0",
      rounded: "full",
      userSelect: "none",
      "&::after": {
        content: '""',
        position: "absolute",
        inset: "0",
        rounded: "full",
        borderWidth: "1px",
        borderColor: "border",
        mixBlendMode: "darken",
      },
      "&[data-size='lg']": { size: "10" },
      "&[data-size='sm']": { size: "6" },
      _dark: { "&::after": { mixBlendMode: "lighten" } },
    },
    image: {
      aspectRatio: "square",
      size: "full",
      rounded: "full",
      objectFit: "cover",
    },
    fallback: {
      display: "flex",
      size: "full",
      alignItems: "center",
      justifyContent: "center",
      rounded: "full",
      bg: "muted",
      fontSize: "sm",
      color: "muted.foreground",
      "[data-slot='avatar'][data-size='sm'] &": { fontSize: "xs" },
    },
    badge: {
      position: "absolute",
      right: "0",
      bottom: "0",
      zIndex: "10",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      rounded: "full",
      bg: "primary",
      color: "primary.foreground",
      backgroundBlendMode: "color",
      ringW: "2",
      ringC: "background",
      userSelect: "none",
      "[data-slot='avatar'][data-size='sm'] &": {
        size: "2",
        "& > svg": { display: "none" },
      },
      "[data-slot='avatar'][data-size='default'] &": {
        size: "2.5",
        "& > svg": { size: "2" },
      },
      "[data-slot='avatar'][data-size='lg'] &": {
        size: "3",
        "& > svg": { size: "2" },
      },
    },
    group: {
      display: "flex",
      "& > * + *": { marginLeft: "-2" },
      "& > [data-slot='avatar']": { ringW: "2", ringC: "background" },
    },
    groupCount: {
      position: "relative",
      display: "flex",
      size: "8",
      flexShrink: "0",
      alignItems: "center",
      justifyContent: "center",
      rounded: "full",
      bg: "muted",
      fontSize: "sm",
      color: "muted.foreground",
      ringW: "2",
      ringC: "background",
      "& > svg": { size: "4" },
      "[data-slot='avatar-group']:has([data-size='lg']) &": {
        size: "10",
        "& > svg": { size: "5" },
      },
      "[data-slot='avatar-group']:has([data-size='sm']) &": {
        size: "6",
        "& > svg": { size: "3" },
      },
    },
  },
});
