import { defineSlotRecipe } from "./define-recipe";

export const calendarRecipe = defineSlotRecipe({
  className: "calendar",
  slots: [
    "container",
    "root",
    "months",
    "month",
    "nav",
    "buttonPrevious",
    "buttonNext",
    "monthCaption",
    "dropdowns",
    "dropdownRoot",
    "dropdown",
    "captionLabel",
    "monthGrid",
    "weekdays",
    "weekday",
    "week",
    "weekNumberHeader",
    "weekNumber",
    "weekNumberCell",
    "day",
    "rangeStart",
    "rangeMiddle",
    "rangeEnd",
    "today",
    "outside",
    "disabled",
    "hidden",
    "chevron",
    "dayButton",
  ],
  base: {
    container: {
      bg: "background",
      p: "3",
      "--cell-radius": "var(--radius-2xl)",
      "--cell-size": "calc(var(--spacing, 0.25rem) * 8)",
      "[data-slot=card-content] &": { bg: "transparent" },
      "[data-slot=popover-content] &": { bg: "transparent" },
      "[dir=rtl] &": {
        "& .rdp-button_next > svg": { transform: "rotate(180deg)" },
        "& .rdp-button_previous > svg": { transform: "rotate(180deg)" },
      },
    },
    root: {
      w: "fit",
    },
    months: {
      position: "relative",
      display: "flex",
      flexDirection: "column",
      gap: "4",
      md: { flexDirection: "row" },
    },
    month: {
      display: "flex",
      w: "full",
      flexDirection: "column",
      gap: "4",
    },
    nav: {
      position: "absolute",
      insetInline: "0",
      top: "0",
      display: "flex",
      w: "full",
      alignItems: "center",
      justifyContent: "space-between",
      gap: "1",
    },
    buttonPrevious: {
      size: "var(--cell-size)",
      p: "0",
      userSelect: "none",
      "&[aria-disabled='true']": { opacity: "0.5" },
    },
    buttonNext: {
      size: "var(--cell-size)",
      p: "0",
      userSelect: "none",
      "&[aria-disabled='true']": { opacity: "0.5" },
    },
    monthCaption: {
      display: "flex",
      h: "var(--cell-size)",
      w: "full",
      alignItems: "center",
      justifyContent: "center",
      px: "var(--cell-size)",
    },
    dropdowns: {
      display: "flex",
      h: "var(--cell-size)",
      w: "full",
      alignItems: "center",
      justifyContent: "center",
      gap: "1.5",
      fontSize: "sm",
      fontWeight: "medium",
    },
    dropdownRoot: {
      position: "relative",
      borderRadius: "var(--cell-radius)",
    },
    dropdown: {
      position: "absolute",
      inset: "0",
      bg: "popover",
      opacity: "0",
    },
    captionLabel: {
      fontWeight: "medium",
      userSelect: "none",
    },
    monthGrid: {
      w: "full",
      borderCollapse: "collapse",
    },
    weekdays: {
      display: "flex",
    },
    weekday: {
      flex: "1",
      borderRadius: "var(--cell-radius)",
      fontSize: "0.8rem",
      fontWeight: "normal",
      color: "muted.foreground",
      userSelect: "none",
    },
    week: {
      mt: "2",
      display: "flex",
      w: "full",
    },
    weekNumberHeader: {
      w: "var(--cell-size)",
      userSelect: "none",
    },
    weekNumber: {
      fontSize: "0.8rem",
      color: "muted.foreground",
      userSelect: "none",
    },
    weekNumberCell: {
      display: "flex",
      size: "var(--cell-size)",
      alignItems: "center",
      justifyContent: "center",
      textAlign: "center",
    },
    day: {
      position: "relative",
      aspectRatio: "square",
      h: "full",
      w: "full",
      borderRadius: "var(--cell-radius)",
      p: "0",
      textAlign: "center",
      userSelect: "none",
      "&:last-child[data-selected=true] button": {
        borderTopRightRadius: "var(--cell-radius)",
        borderBottomRightRadius: "var(--cell-radius)",
      },
    },
    rangeStart: {
      position: "relative",
      isolation: "isolate",
      zIndex: "0",
      borderTopLeftRadius: "var(--cell-radius)",
      borderBottomLeftRadius: "var(--cell-radius)",
      bg: "muted",
      "&::after": {
        content: '""',
        position: "absolute",
        insetBlock: "0",
        right: "0",
        w: "4",
        bg: "muted",
      },
    },
    rangeMiddle: {
      borderRadius: "0",
    },
    rangeEnd: {
      position: "relative",
      isolation: "isolate",
      zIndex: "0",
      borderTopRightRadius: "var(--cell-radius)",
      borderBottomRightRadius: "var(--cell-radius)",
      bg: "muted",
      "&::after": {
        content: '""',
        position: "absolute",
        insetBlock: "0",
        left: "0",
        w: "4",
        bg: "muted",
      },
    },
    today: {
      borderRadius: "var(--cell-radius)",
      bg: "muted",
      color: "foreground",
      "&[data-selected=true]": { borderRadius: "0" },
    },
    outside: {
      color: "muted.foreground",
      "&[aria-selected='true']": { color: "muted.foreground" },
    },
    disabled: {
      color: "muted.foreground",
      opacity: "0.5",
    },
    hidden: {
      visibility: "hidden",
    },
    chevron: {
      size: "4",
    },
    dayButton: {
      position: "relative",
      isolation: "isolate",
      zIndex: "10",
      display: "flex",
      aspectRatio: "square",
      size: "auto",
      w: "full",
      minW: "var(--cell-size)",
      flexDirection: "column",
      gap: "1",
      borderWidth: "0",
      lineHeight: "none",
      fontWeight: "normal",
      "&[data-range-end=true]": {
        borderRadius: "var(--cell-radius)",
        bg: "primary",
        color: "primary.foreground",
      },
      "&[data-range-middle=true]": { borderRadius: "0", bg: "muted", color: "foreground" },
      "&[data-range-start=true]": {
        borderRadius: "var(--cell-radius)",
        bg: "primary",
        color: "primary.foreground",
      },
      "&[data-selected-single=true]": { bg: "primary", color: "primary.foreground" },
      _dark: { _hover: { color: "foreground" } },
      "& > span": { fontSize: "xs", opacity: "0.7" },
      ".group\\/day[data-focused='true'] &": {
        borderColor: "ring",
        ringW: "3",
        ringC: "ring/50",
      },
    },
  },
  variants: {
    captionLayout: {
      label: {
        captionLabel: {
          fontSize: "sm",
        },
      },
      dropdown: {
        captionLabel: {
          display: "flex",
          alignItems: "center",
          gap: "1",
          borderRadius: "var(--cell-radius)",
          fontSize: "sm",
          "& > svg": { size: "3.5", color: "muted.foreground" },
        },
      },
      "dropdown-months": {
        captionLabel: {
          display: "flex",
          alignItems: "center",
          gap: "1",
          borderRadius: "var(--cell-radius)",
          fontSize: "sm",
          "& > svg": { size: "3.5", color: "muted.foreground" },
        },
      },
      "dropdown-years": {
        captionLabel: {
          display: "flex",
          alignItems: "center",
          gap: "1",
          borderRadius: "var(--cell-radius)",
          fontSize: "sm",
          "& > svg": { size: "3.5", color: "muted.foreground" },
        },
      },
    },
    showWeekNumber: {
      true: {
        day: {
          "&:nth-child(2)[data-selected=true] button": {
            borderTopLeftRadius: "var(--cell-radius)",
            borderBottomLeftRadius: "var(--cell-radius)",
          },
        },
      },
      false: {
        day: {
          "&:first-child[data-selected=true] button": {
            borderTopLeftRadius: "var(--cell-radius)",
            borderBottomLeftRadius: "var(--cell-radius)",
          },
        },
      },
    },
  },
  defaultVariants: {
    captionLayout: "label",
    showWeekNumber: false,
  },
});
