import { defineSlotRecipe } from "./define-recipe";

const shadowLg = "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)";

export const comboboxRecipe = defineSlotRecipe({
  className: "combobox",
  slots: [
    "trigger",
    "triggerIcon",
    "inputButton",
    "inputGroupWrapper",
    "positioner",
    "content",
    "list",
    "item",
    "itemIndicator",
    "label",
    "empty",
    "separator",
    "chips",
    "chip",
    "chipRemove",
    "chipsInput",
    "iconNone",
  ],
  base: {
    trigger: {
      "& svg:not([class*='size-'])": { size: "4" },
    },
    triggerIcon: {
      pointerEvents: "none",
      size: "4",
      color: "muted.foreground",
    },
    inputButton: {
      "[data-slot='input-group']:has([data-slot=combobox-clear]) &": { display: "none" },
      "&[data-pressed]": { bg: "transparent" },
    },
    inputGroupWrapper: {
      w: "auto",
    },
    positioner: {
      isolation: "isolate",
      zIndex: "50",
    },
    content: {
      position: "relative",
      maxH: "var(--available-height)",
      w: "var(--anchor-width)",
      maxW: "var(--available-width)",
      minW: "calc(var(--anchor-width) + var(--spacing, 0.25rem) * 7)",
      transformOrigin: "var(--transform-origin)",
      overflow: "hidden",
      rounded: "2xl",
      bg: "popover",
      color: "popover.foreground",
      boxShadow: `0 0 0 1px color-mix(in oklab, var(--foreground) 5%, transparent), ${shadowLg}`,
      "&[data-chips=true]": { minW: "var(--anchor-width)" },
      "& > [data-slot=input-group]": {
        m: "1",
        mb: "0",
        h: "8",
        borderColor: "input/30",
        bg: "input/50",
        boxShadow: "none",
      },
      _dark: {
        boxShadow: `0 0 0 1px color-mix(in oklab, var(--foreground) 10%, transparent), ${shadowLg}`,
      },
    },
    list: {
      maxH: "min(calc(var(--spacing, 0.25rem) * 72 - var(--spacing, 0.25rem) * 9), calc(var(--available-height) - var(--spacing, 0.25rem) * 9))",
      scrollPaddingBlock: "1",
      overflowY: "auto",
      overscrollBehavior: "contain",
      p: "1",
      "&[data-empty]": { p: "0" },
    },
    item: {
      position: "relative",
      display: "flex",
      minH: "7",
      w: "full",
      cursor: "default",
      alignItems: "center",
      gap: "2",
      rounded: "xl",
      py: "1.5",
      pr: "8",
      pl: "2",
      fontSize: "sm",
      outline: "none",
      userSelect: "none",
      "&[data-highlighted]": { bg: "accent", color: "accent.foreground" },
      "&:not([data-variant=destructive])[data-highlighted] *": { color: "accent.foreground" },
      "&[data-disabled]": { pointerEvents: "none", opacity: "0.5" },
      "& svg": { pointerEvents: "none", flexShrink: "0" },
      "& svg:not([class*='size-'])": { size: "4" },
    },
    itemIndicator: {
      pointerEvents: "none",
      position: "absolute",
      right: "2",
      display: "flex",
      size: "4",
      alignItems: "center",
      justifyContent: "center",
    },
    label: {
      px: "2",
      py: "1.5",
      fontSize: "xs",
      color: "muted.foreground",
    },
    empty: {
      display: "none",
      w: "full",
      justifyContent: "center",
      py: "2",
      textAlign: "center",
      fontSize: "sm",
      color: "muted.foreground",
      "[data-slot='combobox-content'][data-empty] &": { display: "flex" },
    },
    separator: {
      mx: "-1",
      my: "1",
      h: "1px",
      bg: "border",
    },
    chips: {
      display: "flex",
      minH: "8",
      flexWrap: "wrap",
      alignItems: "center",
      gap: "1",
      rounded: "2xl",
      borderWidth: "1px",
      borderColor: "transparent",
      bg: "input/50",
      backgroundClip: "padding-box",
      px: "2.5",
      py: "1",
      fontSize: "sm",
      transitionProperty: "color, box-shadow",
      transitionDuration: "200ms",
      _focusWithin: { borderColor: "ring", ringW: "3", ringC: "ring/30" },
      "&:has([aria-invalid='true'])": {
        borderColor: "destructive",
        ringW: "3",
        ringC: "destructive/20",
      },
      "&:has([data-slot=combobox-chip])": { px: "1" },
      _dark: {
        "&:has([aria-invalid='true'])": { borderColor: "destructive/50", ringC: "destructive/40" },
      },
    },
    chip: {
      display: "flex",
      h: "calc(var(--spacing, 0.25rem) * 5.25)",
      w: "fit",
      alignItems: "center",
      justifyContent: "center",
      gap: "1",
      rounded: "2xl",
      bg: "input",
      px: "1.5",
      fontSize: "xs",
      fontWeight: "medium",
      whiteSpace: "nowrap",
      color: "foreground",
      "&:has(:disabled)": { pointerEvents: "none", cursor: "not-allowed", opacity: "0.5" },
      "&:has([data-slot=combobox-chip-remove])": { pr: "0.5" },
      _dark: { bg: "input/60" },
    },
    chipRemove: {
      ml: "-0.5",
      size: "4.5",
      opacity: "0.5",
      _hover: { opacity: "1" },
      "&[aria-disabled='true']": { pointerEvents: "none" },
    },
    chipsInput: {
      minW: "16",
      flex: "1",
      outline: "none",
    },
    iconNone: {
      pointerEvents: "none",
    },
  },
});
