import { defineSlotRecipe } from "./define-recipe";

export const commandRecipe = defineSlotRecipe({
  className: "command",
  slots: [
    "root",
    "dialogContent",
    "inputWrapper",
    "inputGroup",
    "input",
    "inputIcon",
    "list",
    "empty",
    "group",
    "separator",
    "item",
    "itemCheck",
    "shortcut",
  ],
  base: {
    root: {
      display: "flex",
      size: "full",
      flexDirection: "column",
      overflow: "hidden",
      rounded: "3xl",
      bg: "popover",
      p: "1",
      color: "popover.foreground",
    },
    dialogContent: {
      top: "33.333333%",
      transform: "translateX(-50%)!",
      overflow: "hidden",
      borderRadius: "3xl!",
      p: "0",
    },
    inputWrapper: {
      p: "1",
      pb: "0",
    },
    inputGroup: {
      h: "8!",
      bg: "input/50",
    },
    input: {
      w: "full",
      fontSize: "sm",
      outline: "none",
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
    },
    inputIcon: {
      size: "4",
      flexShrink: "0",
      opacity: "0.5",
    },
    list: {
      maxH: "72",
      scrollPaddingBlock: "1",
      overflowX: "hidden",
      overflowY: "auto",
      outline: "none",
    },
    empty: {
      py: "6",
      textAlign: "center",
      fontSize: "sm",
    },
    group: {
      overflow: "hidden",
      p: "1",
      color: "foreground",
      "& [cmdk-group-heading]": {
        px: "2",
        py: "1.5",
        fontSize: "xs",
        fontWeight: "medium",
        color: "muted.foreground",
      },
    },
    separator: {
      my: "1",
      h: "1px",
      bg: "border/50",
    },
    item: {
      position: "relative",
      display: "flex",
      minH: "7",
      cursor: "default",
      alignItems: "center",
      gap: "2",
      rounded: "xl",
      px: "2",
      py: "1.5",
      fontSize: "sm",
      outline: "none",
      userSelect: "none",
      "[data-slot=dialog-content] &": { rounded: "2xl" },
      "&[data-disabled=true]": { pointerEvents: "none", opacity: "0.5" },
      "&[data-selected='true']": { bg: "muted", color: "foreground" },
      "& svg": { pointerEvents: "none", flexShrink: "0" },
      "& svg:not([class*='size-'])": { size: "4" },
      "&[data-selected='true'] > svg": { color: "foreground" },
    },
    itemCheck: {
      ml: "auto",
      opacity: "0",
      "[data-slot='command-item']:has([data-slot=command-shortcut]) &": { display: "none" },
      "[data-slot='command-item'][data-checked=true] &": { opacity: "1" },
    },
    shortcut: {
      ml: "auto",
      fontSize: "xs",
      letterSpacing: "widest",
      color: "muted.foreground",
      "[data-slot='command-item'][data-selected='true'] &": { color: "foreground" },
    },
  },
});
