import { defineSlotRecipe } from "./define-recipe";

const shadowLg = "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)";
const EASE = "cubic-bezier(0.4, 0, 0.2, 1)";

export const contextMenuRecipe = defineSlotRecipe({
  className: "context-menu",
  slots: [
    "trigger",
    "positioner",
    "content",
    "label",
    "item",
    "subTrigger",
    "subTriggerIcon",
    "checkRadioItem",
    "indicator",
    "separator",
    "shortcut",
  ],
  base: {
    trigger: {
      userSelect: "none",
    },
    positioner: {
      isolation: "isolate",
      zIndex: "50",
      outline: "none",
    },
    content: {
      zIndex: "50",
      maxH: "var(--available-height)",
      minW: "36",
      transformOrigin: "var(--transform-origin)",
      overflowX: "hidden",
      overflowY: "auto",
      rounded: "2xl",
      bg: "popover",
      p: "1",
      color: "popover.foreground",
      outline: "none",
      boxShadow: `0 0 0 1px color-mix(in oklab, var(--foreground) 5%, transparent), ${shadowLg}`,
      _dark: {
        boxShadow: `0 0 0 1px color-mix(in oklab, var(--foreground) 10%, transparent), ${shadowLg}`,
      },
      // popoverAnimationStyles inlined
      transitionProperty: "opacity, scale, translate",
      transitionTimingFunction: EASE,
      transitionDuration: "100ms",
      "&[data-starting-style]": { opacity: "0", scale: "0.95" },
      "&[data-ending-style]": { opacity: "0", scale: "0.95" },
      "&[data-side='top'][data-starting-style]": { translate: "0 0.5rem" },
      "&[data-side='bottom'][data-starting-style]": { translate: "0 -0.5rem" },
      "&[data-side='left'][data-starting-style]": { translate: "0.5rem" },
      "&[data-side='right'][data-starting-style]": { translate: "-0.5rem" },
      "&[data-side='inline-start'][data-starting-style]": { translate: "0.5rem" },
      "&[data-side='inline-end'][data-starting-style]": { translate: "-0.5rem" },
    },
    label: {
      px: "2",
      py: "1",
      fontSize: "xs",
      color: "muted.foreground",
      "&[data-inset]": { pl: "7" },
    },
    item: {
      position: "relative",
      display: "flex",
      minH: "7",
      cursor: "default",
      alignItems: "center",
      gap: "2",
      rounded: "xl",
      px: "2",
      py: "1.5",
      fontSize: "sm",
      outline: "none",
      userSelect: "none",
      _focus: { bg: "accent", color: "accent.foreground" },
      "&[data-inset]": { pl: "7" },
      "&[data-variant=destructive]": { color: "destructive" },
      "&[data-variant=destructive]:focus": { bg: "destructive/10", color: "destructive" },
      "&:where([data-disabled]:not([data-disabled='false']))": {
        pointerEvents: "none",
        opacity: "0.5",
      },
      "& svg": { pointerEvents: "none", flexShrink: "0" },
      "& svg:not([class*='size-'])": { size: "4" },
      "&:focus > svg": { color: "accent.foreground" },
      "&[data-variant=destructive] > svg": { color: "destructive" },
      _dark: { "&[data-variant=destructive]:focus": { bg: "destructive/20" } },
    },
    subTrigger: {
      display: "flex",
      minH: "7",
      cursor: "default",
      alignItems: "center",
      rounded: "xl",
      px: "2",
      py: "1.5",
      fontSize: "sm",
      outline: "none",
      userSelect: "none",
      _focus: { bg: "accent", color: "accent.foreground" },
      "&[data-inset]": { pl: "7" },
      "&:where([data-state='open'], [data-open]:not([data-open='false']))": {
        bg: "accent",
        color: "accent.foreground",
      },
      "& svg": { pointerEvents: "none", flexShrink: "0" },
      "& svg:not([class*='size-'])": { size: "4" },
    },
    subTriggerIcon: {
      ml: "auto",
    },
    checkRadioItem: {
      position: "relative",
      display: "flex",
      minH: "7",
      cursor: "default",
      alignItems: "center",
      gap: "2",
      rounded: "xl",
      py: "1.5",
      pr: "8",
      pl: "2",
      fontSize: "sm",
      outline: "none",
      userSelect: "none",
      _focus: { bg: "accent", color: "accent.foreground" },
      "&[data-inset]": { pl: "7" },
      "&:where([data-disabled]:not([data-disabled='false']))": {
        pointerEvents: "none",
        opacity: "0.5",
      },
      "& svg": { pointerEvents: "none", flexShrink: "0" },
      "& svg:not([class*='size-'])": { size: "4" },
    },
    indicator: {
      pointerEvents: "none",
      position: "absolute",
      right: "2",
    },
    separator: {
      mx: "-1",
      my: "1",
      h: "1px",
      bg: "border/50",
    },
    shortcut: {
      ml: "auto",
      fontSize: "xs",
      letterSpacing: "widest",
      color: "muted.foreground",
      "[data-slot='context-menu-item']:focus &": { color: "accent.foreground" },
    },
  },
});
