import { defineSlotRecipe } from "./define-recipe";

export const fieldRecipe = defineSlotRecipe({
  className: "field",
  slots: [
    "set",
    "legend",
    "group",
    "root",
    "content",
    "label",
    "title",
    "description",
    "separator",
    "separatorLine",
    "separatorContent",
    "error",
    "errorList",
  ],
  base: {
    set: {
      display: "flex",
      flexDirection: "column",
      gap: "6",
      "&:has(> [data-slot='checkbox-group'])": { gap: "3" },
      "&:has(> [data-slot='radio-group'])": { gap: "3" },
    },
    legend: {
      mb: "3",
      fontWeight: "medium",
      "&[data-variant='label']": { fontSize: "sm" },
      "&[data-variant='legend']": { fontSize: "1rem" },
    },
    group: {
      containerType: "inline-size",
      containerName: "field-group",
      display: "flex",
      w: "full",
      flexDirection: "column",
      gap: "6",
      "&[data-slot='checkbox-group']": { gap: "3" },
      "& > [data-slot='field-group']": { gap: "4" },
    },
    root: {
      display: "flex",
      w: "full",
      gap: "3",
      "&[data-invalid='true']": { color: "destructive" },
    },
    content: {
      display: "flex",
      flex: "1",
      flexDirection: "column",
      gap: "1",
      lineHeight: "snug",
    },
    label: {
      display: "flex",
      w: "fit",
      gap: "2",
      lineHeight: "snug",
      "[data-slot='field'][data-disabled='true'] &": { opacity: "0.5" },
      "&:has(:where([data-state='checked'], [data-checked]:not([data-checked='false'])))": {
        bg: "input/30",
      },
      "&:has(> [data-slot='field'])": {
        rounded: "2xl",
        borderWidth: "1px",
        w: "full",
        flexDirection: "column",
      },
      "& > [data-slot='field']": { p: "4" },
    },
    title: {
      display: "flex",
      w: "fit",
      alignItems: "center",
      gap: "2",
      fontSize: "sm",
      fontWeight: "medium",
      "[data-slot='field'][data-disabled='true'] &": { opacity: "0.5" },
    },
    description: {
      textAlign: "left",
      fontSize: "sm",
      lineHeight: "normal",
      fontWeight: "normal",
      color: "muted.foreground",
      "[data-slot='field']:has([data-orientation='horizontal']) &": { textWrap: "balance" },
      "[data-variant='legend'] + &": { mt: "-0.375rem" },
      _last: { mt: "0" },
      "&:nth-last-child(2)": { mt: "-0.25rem" },
      "& > a": { textDecoration: "underline", textUnderlineOffset: "4px" },
      "& > a:hover": { color: "primary" },
    },
    separator: {
      position: "relative",
      marginBlock: "-0.5rem",
      h: "5",
      fontSize: "sm",
      "[data-slot='field-group'][data-variant='outline'] &": { mb: "-0.5rem" },
    },
    separatorLine: { position: "absolute", inset: "0", top: "50%" },
    separatorContent: {
      position: "relative",
      mx: "auto",
      display: "block",
      w: "fit",
      bg: "background",
      px: "2",
      color: "muted.foreground",
    },
    error: { fontSize: "sm", fontWeight: "normal", color: "destructive" },
    errorList: {
      ml: "4",
      display: "flex",
      listStyleType: "disc",
      flexDirection: "column",
      gap: "1",
    },
  },
  variants: {
    orientation: {
      vertical: {
        root: {
          flexDirection: "column",
          "& > *": { w: "full" },
          "& > .sr-only": { w: "auto" },
        },
      },
      horizontal: {
        root: {
          flexDirection: "row",
          alignItems: "center",
          "&:has(> [data-slot='field-content'])": { alignItems: "flex-start" },
          "& > [data-slot='field-label']": { flex: "auto" },
          "&:has(> [data-slot='field-content']) > :is([role=checkbox], [role=radio])": { mt: "px" },
        },
      },
      responsive: {
        root: {
          flexDirection: "column",
          "& > *": { w: "full" },
          "& > .sr-only": { w: "auto" },
          "@container field-group (min-width: 28rem)": {
            flexDirection: "row",
            alignItems: "center",
            "& > *": { w: "auto" },
            "&:has(> [data-slot='field-content'])": { alignItems: "flex-start" },
            "& > [data-slot='field-label']": { flex: "auto" },
            "&:has(> [data-slot='field-content']) > :is([role=checkbox], [role=radio])": {
              mt: "px",
            },
          },
        },
      },
    },
  },
  defaultVariants: {
    orientation: "vertical",
  },
});
