import { defineSlotRecipe } from "./define-recipe";

export const menubarRecipe = defineSlotRecipe({
  className: "menubar",
  slots: [
    "root",
    "trigger",
    "content",
    "item",
    "checkboxItem",
    "radioItem",
    "indicator",
    "label",
    "shortcut",
    "subContent",
  ],
  base: {
    root: {
      display: "flex",
      h: "8",
      alignItems: "center",
      rounded: "2xl",
      borderWidth: "1px",
      p: "3px",
    },
    trigger: {
      display: "flex",
      alignItems: "center",
      rounded: "2xl",
      px: "1.5",
      py: "2px",
      fontSize: "sm",
      fontWeight: "medium",
      outline: "none",
      userSelect: "none",
      _hover: { bg: "muted" },
      "&[aria-expanded='true']": { bg: "muted" },
    },
    // Overrides the dropdown content base (minW:32 → 36); `!important` beats the
    // non-important base value (Panda atomics don't twMerge-dedupe).
    content: {
      minW: "36!",
    },
    item: {
      minH: "7",
      gap: "2",
      rounded: "xl",
      px: "2",
      py: "1.5",
      fontSize: "sm",
      _focus: { bg: "accent", color: "accent.foreground" },
      "&:not([data-variant=destructive]):focus *": { color: "accent.foreground" },
      "&[data-inset]": { pl: "7" },
      "&[data-variant=destructive]": { color: "destructive" },
      "&[data-variant=destructive]:focus": { bg: "destructive/10", color: "destructive" },
      "&:where([data-disabled]:not([data-disabled='false']))": { opacity: "0.5" },
      "& svg:not([class*='size-'])": { size: "4" },
      "&[data-variant=destructive] > svg": { color: "destructive!" },
      _dark: { "&[data-variant=destructive]:focus": { bg: "destructive/20" } },
    },
    checkboxItem: {
      position: "relative",
      display: "flex",
      minH: "7",
      cursor: "default",
      alignItems: "center",
      gap: "2",
      rounded: "xl",
      py: "1.5",
      pr: "1.5",
      pl: "7",
      fontSize: "sm",
      outline: "none",
      userSelect: "none",
      _focus: { bg: "accent", color: "accent.foreground" },
      "&:focus *": { color: "accent.foreground" },
      "&[data-inset]": { pl: "7" },
      "&:where([data-disabled]:not([data-disabled='false']))": {
        pointerEvents: "none",
        opacity: "0.5",
      },
      "& svg": { pointerEvents: "none", flexShrink: "0" },
    },
    radioItem: {
      position: "relative",
      display: "flex",
      minH: "7",
      cursor: "default",
      alignItems: "center",
      gap: "2",
      rounded: "xl",
      py: "1.5",
      pr: "1.5",
      pl: "7",
      fontSize: "sm",
      outline: "none",
      userSelect: "none",
      _focus: { bg: "accent", color: "accent.foreground" },
      "&:focus *": { color: "accent.foreground" },
      "&[data-inset]": { pl: "7" },
      "&:where([data-disabled]:not([data-disabled='false']))": {
        pointerEvents: "none",
        opacity: "0.5",
      },
      "& svg": { pointerEvents: "none", flexShrink: "0" },
      "& svg:not([class*='size-'])": { size: "4" },
    },
    indicator: {
      pointerEvents: "none",
      position: "absolute",
      left: "1.5",
      display: "flex",
      size: "4",
      alignItems: "center",
      justifyContent: "center",
      "& svg:not([class*='size-'])": { size: "4" },
    },
    label: {
      fontSize: "sm!",
    },
    shortcut: {
      "[data-slot='menubar-item']:focus &": { color: "accent.foreground" },
    },
    // Overrides the dropdown sub-content base (minW:96px! → 32). Needs the
    // data-slot self-selector so its `!important` beats the base's `!important`
    // (higher specificity wins among important declarations).
    subContent: {
      "&[data-slot='menubar-sub-content']": { minW: "32!" },
    },
  },
});
