import { defineSlotRecipe } from "./define-recipe";

const shadowLg = "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)";
const ringShadow = (pct: string) =>
  `0 0 0 1px color-mix(in oklab, var(--foreground) ${pct}, transparent), ${shadowLg}`;

export const navigationMenuRecipe = defineSlotRecipe({
  className: "navigation-menu",
  slots: [
    "root",
    "list",
    "item",
    "trigger",
    "triggerIcon",
    "content",
    "positioner",
    "popup",
    "viewport",
    "link",
    "indicator",
    "indicatorArrow",
  ],
  base: {
    root: {
      position: "relative",
      display: "flex",
      maxW: "max-content",
      flex: "1",
      alignItems: "center",
      justifyContent: "center",
    },
    list: {
      display: "flex",
      flex: "1",
      listStyleType: "none",
      alignItems: "center",
      justifyContent: "center",
      gap: "0",
    },
    item: { position: "relative" },
    trigger: {
      display: "inline-flex",
      h: "9",
      w: "max-content",
      alignItems: "center",
      justifyContent: "center",
      rounded: "2xl",
      px: "2.5",
      py: "1.5",
      fontSize: "sm",
      fontWeight: "medium",
      transitionProperty: "all",
      transitionTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
      transitionDuration: "150ms",
      outline: "none",
      _hover: { bg: "muted" },
      _focus: { bg: "muted" },
      _focusVisible: { ringW: "3", ringC: "ring/30", outlineWidth: "1px" },
      _disabled: { pointerEvents: "none", opacity: "0.5" },
      "&[data-popup-open]": { bg: "muted/50", _hover: { bg: "muted" } },
      "&:where([data-state='open'], [data-open]:not([data-open='false']))": {
        bg: "muted/50",
        _hover: { bg: "muted" },
        _focus: { bg: "muted" },
      },
    },
    triggerIcon: {
      position: "relative",
      top: "1px",
      ml: "1",
      size: "3",
      transitionProperty: "rotate",
      transitionDuration: "300ms",
      "[data-slot='navigation-menu-trigger'][data-popup-open] &": { rotate: "180deg" },
    },
    content: {
      h: "full",
      w: "auto",
      p: "1.5",
      transitionProperty: "opacity, transform, translate",
      transitionDuration: "0.35s",
      transitionTimingFunction: "cubic-bezier(0.22, 1, 0.36, 1)",
      "&[data-ending-style][data-activation-direction=left]": { translate: "50%" },
      "&[data-ending-style][data-activation-direction=right]": { translate: "-50%" },
      "&[data-starting-style][data-activation-direction=left]": { translate: "-50%" },
      "&[data-starting-style][data-activation-direction=right]": { translate: "50%" },
      "&[data-ending-style]": { opacity: "0" },
      "&[data-starting-style]": { opacity: "0" },
      "& [data-slot=navigation-menu-link]:focus": { ringW: "0", outline: "none" },
    },
    positioner: {
      isolation: "isolate",
      zIndex: "50",
      h: "var(--positioner-height)",
      w: "var(--positioner-width)",
      maxW: "var(--available-width)",
      transitionProperty: "top, left, right, bottom",
      transitionDuration: "0.35s",
      transitionTimingFunction: "cubic-bezier(0.22, 1, 0.36, 1)",
      "&[data-instant]": { transition: "none" },
      "&[data-side=bottom]::before": { content: '""', top: "-10px", right: "0", left: "0" },
    },
    popup: {
      position: "relative",
      h: "var(--popup-height)",
      w: "var(--popup-width)",
      transformOrigin: "var(--transform-origin)",
      rounded: "3xl",
      bg: "popover",
      color: "popover.foreground",
      boxShadow: ringShadow("5%"),
      transitionProperty: "opacity, transform, width, height, scale, translate",
      transitionDuration: "0.35s",
      transitionTimingFunction: "cubic-bezier(0.22, 1, 0.36, 1)",
      outline: "none",
      "&[data-ending-style]": {
        scale: "0.9",
        opacity: "0",
        transitionDuration: "150ms",
        transitionTimingFunction: "ease",
      },
      "&[data-starting-style]": { scale: "0.9", opacity: "0" },
      _dark: { boxShadow: ringShadow("10%") },
    },
    viewport: { position: "relative", size: "full", overflow: "hidden" },
    link: {
      display: "flex",
      alignItems: "center",
      gap: "2",
      rounded: "2xl",
      px: "2.5",
      py: "1.5",
      fontSize: "sm",
      fontWeight: "medium",
      transitionProperty: "all",
      transitionTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
      transitionDuration: "150ms",
      outline: "none",
      _hover: { bg: "muted" },
      _focus: { bg: "muted" },
      _focusVisible: { ringW: "3", ringC: "ring/30", outlineWidth: "1px" },
      "[data-slot=navigation-menu-content] &": {
        w: "full",
        rounded: "xl",
        p: "2",
        fontWeight: "normal",
      },
      "&[data-active=true]": {
        bg: "muted/50",
        _hover: { bg: "muted" },
        _focus: { bg: "muted" },
      },
      "& svg:not([class*='size-'])": { size: "4" },
    },
    indicator: {
      top: "full",
      zIndex: "1",
      display: "flex",
      h: "1.5",
      alignItems: "flex-end",
      justifyContent: "center",
      overflow: "hidden",
    },
    indicatorArrow: {
      position: "relative",
      top: "60%",
      h: "2",
      w: "2",
      rotate: "45deg",
      borderTopLeftRadius: "sm",
      bg: "border",
      boxShadow: "md",
    },
  },
});
