import { defineSlotRecipe } from "./define-recipe";

const shadowLg = "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)";

const EASE = "cubic-bezier(0.4, 0, 0.2, 1)";

export const selectRecipe = defineSlotRecipe({
  className: "select",
  slots: [
    "group",
    "value",
    "trigger",
    "triggerIcon",
    "positioner",
    "content",
    "label",
    "item",
    "itemText",
    "itemIndicator",
    "checkIcon",
    "separator",
    "scrollUpButton",
    "scrollDownButton",
  ],
  base: {
    group: {
      scrollMarginBlock: "1.5",
      p: "1",
    },
    value: {
      display: "flex",
      flex: "1",
      textAlign: "left",
    },
    trigger: {
      display: "flex",
      w: "fit",
      alignItems: "center",
      justifyContent: "space-between",
      gap: "1.5",
      rounded: "2xl",
      borderWidth: "1px",
      borderColor: "transparent",
      bg: "input/50",
      px: "3",
      py: "2",
      fontSize: "sm",
      whiteSpace: "nowrap",
      transitionProperty: "color, box-shadow",
      transitionDuration: "200ms",
      outline: "none",
      _focusVisible: { borderColor: "ring", ringW: "3", ringC: "ring/30" },
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
      "&[aria-invalid='true']": { borderColor: "destructive", ringW: "3", ringC: "destructive/20" },
      "&[data-placeholder]": { color: "muted.foreground" },
      "&[data-size=default]": { h: "8" },
      "&[data-size=sm]": { h: "7" },
      "& > [data-slot=select-value]": {
        display: "flex",
        overflow: "hidden",
        alignItems: "center",
        gap: "1.5",
      },
      "& svg": { pointerEvents: "none", flexShrink: "0" },
      "& svg:not([class*='size-'])": { size: "4" },
      _dark: {
        "&[aria-invalid='true']": { borderColor: "destructive/50", ringC: "destructive/40" },
      },
    },
    triggerIcon: {
      pointerEvents: "none",
      size: "4",
      color: "muted.foreground",
    },
    positioner: {
      isolation: "isolate",
      zIndex: "50",
    },
    content: {
      position: "relative",
      isolation: "isolate",
      zIndex: "50",
      maxH: "var(--available-height)",
      w: "var(--anchor-width)",
      minW: "36",
      transformOrigin: "var(--transform-origin)",
      overflowX: "hidden",
      overflowY: "auto",
      rounded: "2xl",
      bg: "popover",
      color: "popover.foreground",
      boxShadow: `0 0 0 1px color-mix(in oklab, var(--foreground) 5%, transparent), ${shadowLg}`,
      _dark: {
        boxShadow: `0 0 0 1px color-mix(in oklab, var(--foreground) 10%, transparent), ${shadowLg}`,
      },
      // Select animation (fade + zoom + directional slide, suppressed when aligned to trigger)
      transitionProperty: "opacity, scale, translate",
      transitionTimingFunction: EASE,
      transitionDuration: "100ms",
      "&[data-align-trigger='false']": {
        "&[data-starting-style]": { opacity: "0", scale: "0.95" },
        "&[data-ending-style]": { opacity: "0", scale: "0.95" },
        "&[data-side='top'][data-starting-style]": { translate: "0 0.5rem" },
        "&[data-side='bottom'][data-starting-style]": { translate: "0 -0.5rem" },
        "&[data-side='left'][data-starting-style]": { translate: "0.5rem" },
        "&[data-side='right'][data-starting-style]": { translate: "-0.5rem" },
        "&[data-side='inline-start'][data-starting-style]": { translate: "0.5rem" },
        "&[data-side='inline-end'][data-starting-style]": { translate: "-0.5rem" },
      },
    },
    label: {
      px: "2",
      py: "1",
      fontSize: "xs",
      color: "muted.foreground",
    },
    item: {
      position: "relative",
      display: "flex",
      minH: "7",
      w: "full",
      cursor: "default",
      alignItems: "center",
      gap: "2",
      rounded: "xl",
      py: "1.5",
      pr: "8",
      pl: "2",
      fontSize: "sm",
      outline: "none",
      userSelect: "none",
      _focus: { bg: "accent", color: "accent.foreground" },
      "&:not([data-variant=destructive]):focus *": { color: "accent.foreground" },
      "&:where([data-disabled]:not([data-disabled='false']))": {
        pointerEvents: "none",
        opacity: "0.5",
      },
      "& svg": { pointerEvents: "none", flexShrink: "0" },
      "& svg:not([class*='size-'])": { size: "4" },
      "& > span:last-child": { display: "flex", alignItems: "center", gap: "2" },
    },
    itemText: {
      display: "flex",
      flex: "1",
      flexShrink: "0",
      gap: "2",
      whiteSpace: "nowrap",
    },
    itemIndicator: {
      pointerEvents: "none",
      position: "absolute",
      right: "2",
      display: "flex",
      size: "4",
      alignItems: "center",
      justifyContent: "center",
    },
    checkIcon: {
      pointerEvents: "none",
    },
    separator: {
      pointerEvents: "none",
      mx: "-1",
      my: "1",
      h: "1px",
      bg: "border",
    },
    scrollUpButton: {
      zIndex: "10",
      display: "flex",
      w: "full",
      cursor: "default",
      alignItems: "center",
      justifyContent: "center",
      bg: "popover",
      py: "1",
      top: "0",
      "& svg:not([class*='size-'])": { size: "4" },
    },
    scrollDownButton: {
      zIndex: "10",
      display: "flex",
      w: "full",
      cursor: "default",
      alignItems: "center",
      justifyContent: "center",
      bg: "popover",
      py: "1",
      bottom: "0",
      "& svg:not([class*='size-'])": { size: "4" },
    },
  },
});
