import { defineSlotRecipe } from "./define-recipe";

export const sheetRecipe = defineSlotRecipe({
  className: "sheet",
  slots: ["overlay", "content", "closeButton", "header", "footer", "title", "description"],
  base: {
    overlay: {
      position: "fixed",
      inset: "0",
      zIndex: "50",
      bg: "black/30",
      transitionProperty: "opacity",
      transitionTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
      transitionDuration: "150ms",
      "&[data-ending-style]": { opacity: "0" },
      "&[data-starting-style]": { opacity: "0" },
      "@supports ((backdrop-filter: blur(0)) or (-webkit-backdrop-filter: blur(0)))": {
        backdropFilter: "blur(4px)",
      },
    },
    content: {
      position: "fixed",
      zIndex: "50",
      display: "flex",
      flexDirection: "column",
      bg: "popover",
      backgroundClip: "padding-box",
      fontSize: "sm",
      color: "popover.foreground",
      boxShadow: "xl",
      transitionProperty: "opacity, translate",
      transitionTimingFunction: "ease-in-out",
      transitionDuration: "200ms",
      "&[data-ending-style]": { opacity: "0" },
      "&[data-starting-style]": { opacity: "0" },
      "&[data-side='bottom']": {
        insetInline: "0",
        bottom: "0",
        h: "auto",
        borderTopWidth: "1px",
        "&[data-ending-style]": { translate: "0 2.5rem" },
        "&[data-starting-style]": { translate: "0 2.5rem" },
      },
      "&[data-side='left']": {
        insetBlock: "0",
        left: "0",
        h: "full",
        w: "75%",
        borderRightWidth: "1px",
        sm: { maxW: "sm" },
        "&[data-ending-style]": { translate: "-2.5rem" },
        "&[data-starting-style]": { translate: "-2.5rem" },
      },
      "&[data-side='right']": {
        insetBlock: "0",
        right: "0",
        h: "full",
        w: "75%",
        borderLeftWidth: "1px",
        sm: { maxW: "sm" },
        "&[data-ending-style]": { translate: "2.5rem" },
        "&[data-starting-style]": { translate: "2.5rem" },
      },
      "&[data-side='top']": {
        insetInline: "0",
        top: "0",
        h: "auto",
        borderBottomWidth: "1px",
        "&[data-ending-style]": { translate: "0 -2.5rem" },
        "&[data-starting-style]": { translate: "0 -2.5rem" },
      },
    },
    closeButton: { position: "absolute", top: "4", right: "4", bg: "secondary" },
    header: { display: "flex", flexDirection: "column", gap: "1.5", p: "6" },
    footer: {
      mt: "auto",
      display: "flex",
      flexDirection: "column",
      gap: "2",
      p: "6",
    },
    title: {
      fontFamily: "var(--font-heading)",
      fontSize: "1rem",
      fontWeight: "medium",
      color: "foreground",
    },
    description: { fontSize: "sm", color: "muted.foreground" },
  },
});
