import { defineSlotRecipe } from "./define-recipe";

export const sidebarRecipe = defineSlotRecipe({
  className: "sidebar",
  slots: [
    "wrapper",
    "none",
    "mobile",
    "mobileInner",
    "desktop",
    "gap",
    "container",
    "inner",
    "rail",
    "inset",
    "input",
    "header",
    "footer",
    "separator",
    "content",
    "group",
    "groupLabel",
    "groupAction",
    "groupContent",
    "menu",
    "menuItem",
    "menuButton",
    "menuAction",
    "menuBadge",
    "menuSkeleton",
    "menuSkeletonIcon",
    "menuSkeletonText",
    "menuSub",
    "menuSubItem",
    "menuSubButton",
  ],
  base: {
    wrapper: {
      display: "flex",
      minH: "100svh",
      w: "full",
      "&:has([data-variant=inset])": { bg: "sidebar" },
    },
    none: {
      display: "flex",
      h: "full",
      w: "var(--sidebar-width)",
      flexDirection: "column",
      bg: "sidebar",
      color: "sidebar.foreground",
    },
    mobile: {
      w: "var(--sidebar-width)",
      bg: "sidebar",
      p: "0",
      color: "sidebar.foreground",
      "& > button": { display: "none" },
    },
    mobileInner: {
      display: "flex",
      h: "full",
      w: "full",
      flexDirection: "column",
    },
    desktop: {
      display: "none",
      color: "sidebar.foreground",
      md: { display: "block" },
    },
    gap: {
      position: "relative",
      w: "var(--sidebar-width)",
      bg: "transparent",
      transitionProperty: "width",
      transitionDuration: "200ms",
      transitionTimingFunction: "linear",
      "[data-slot='sidebar'][data-collapsible=offcanvas] &": { w: "0" },
      "[data-slot='sidebar'][data-side=right] &": { rotate: "180deg" },
    },
    container: {
      position: "fixed",
      insetBlock: "0",
      zIndex: "10",
      display: "none",
      h: "100svh",
      w: "var(--sidebar-width)",
      transitionProperty: "left, right, width",
      transitionDuration: "200ms",
      transitionTimingFunction: "linear",
      md: { display: "flex" },
      "&[data-side=left]": { left: "0" },
      "&[data-side=right]": { right: "0" },
      "[data-slot='sidebar'][data-collapsible=offcanvas] &": {
        "&[data-side=left]": { left: "calc(var(--sidebar-width) * -1)" },
        "&[data-side=right]": { right: "calc(var(--sidebar-width) * -1)" },
      },
    },
    inner: {
      display: "flex",
      size: "full",
      flexDirection: "column",
      bg: "sidebar",
      "[data-slot='sidebar'][data-variant=floating] &": {
        rounded: "2xl",
        boxShadow: "sm",
        ringW: "1",
        ringC: "sidebar.border",
      },
    },
    rail: {
      position: "absolute",
      insetBlock: "0",
      zIndex: "20",
      display: "none",
      w: "4",
      transitionProperty: "all",
      transitionTimingFunction: "linear",
      transform: "translateX(-50%)",
      sm: { display: "flex" },
      "[data-slot='sidebar'][data-side=left] &": { right: "-4" },
      "[data-slot='sidebar'][data-side=right] &": { left: "0" },
      "&::after": {
        content: '""',
        position: "absolute",
        insetBlock: "0",
        insetInlineStart: "50%",
        w: "2px",
      },
      "&:hover::after": { bg: "sidebar.border" },
      "[data-side=left] &": { cursor: "w-resize" },
      "[data-side=right] &": { cursor: "e-resize" },
      "[data-side=left][data-state=collapsed] &": { cursor: "e-resize" },
      "[data-side=right][data-state=collapsed] &": { cursor: "w-resize" },
      "[data-slot='sidebar'][data-collapsible=offcanvas] &": {
        transform: "translateX(0)",
        "&::after": { left: "full" },
        _hover: { bg: "sidebar" },
      },
      "[data-side=left][data-collapsible=offcanvas] &": { right: "-2" },
      "[data-side=right][data-collapsible=offcanvas] &": { left: "-2" },
    },
    inset: {
      position: "relative",
      display: "flex",
      w: "full",
      flex: "1",
      flexDirection: "column",
      bg: "background",
      "[data-slot='sidebar'][data-variant=inset] ~ &": {
        md: { m: "2", ml: "0", rounded: "2xl", boxShadow: "sm" },
      },
      "[data-slot='sidebar'][data-variant=inset][data-state=collapsed] ~ &": {
        md: { ml: "2" },
      },
    },
    input: { h: "8", w: "full", bg: "input/50", boxShadow: "none" },
    header: {
      display: "flex",
      flexDirection: "column",
      gap: "2",
      p: "2",
      "--radius": "var(--radius-xl)",
    },
    footer: { display: "flex", flexDirection: "column", gap: "2", p: "2" },
    separator: { mx: "2", w: "auto", bg: "sidebar.border" },
    content: {
      display: "flex",
      minH: "0",
      flex: "1",
      flexDirection: "column",
      gap: "2",
      overflow: "auto",
      "--radius": "var(--radius-xl)",
      "[data-slot='sidebar'][data-collapsible=icon] &": { overflow: "hidden" },
    },
    group: {
      position: "relative",
      display: "flex",
      w: "full",
      minW: "0",
      flexDirection: "column",
      p: "2",
    },
    groupLabel: {
      display: "flex",
      h: "8",
      flexShrink: "0",
      alignItems: "center",
      rounded: "xl",
      px: "3",
      fontSize: "xs",
      fontWeight: "medium",
      color: "sidebar.foreground/70",
      ringC: "sidebar.ring",
      outline: "none",
      transitionProperty: "margin, opacity",
      transitionDuration: "200ms",
      transitionTimingFunction: "linear",
      _focusVisible: { ringW: "3" },
      "[data-slot='sidebar'][data-collapsible=icon] &": { mt: "-8", opacity: "0" },
      "& > svg": { size: "4", flexShrink: "0" },
    },
    groupAction: {
      position: "absolute",
      top: "3.5",
      right: "3",
      display: "flex",
      aspectRatio: "square",
      w: "5",
      alignItems: "center",
      justifyContent: "center",
      rounded: "xl",
      p: "0",
      color: "sidebar.foreground",
      ringC: "sidebar.ring",
      outline: "none",
      transitionProperty: "transform",
      "[data-slot='sidebar'][data-collapsible=icon] &": { display: "none" },
      "&::after": { content: '""', position: "absolute", inset: "-2" },
      _hover: { bg: "sidebar.accent", color: "sidebar.accent.foreground" },
      _focusVisible: { ringW: "3" },
      md: { "&::after": { display: "none" } },
      "& > svg": { size: "4", flexShrink: "0" },
    },
    groupContent: { w: "full", fontSize: "sm" },
    menu: {
      display: "flex",
      w: "full",
      minW: "0",
      flexDirection: "column",
      gap: "0.5",
    },
    menuItem: { position: "relative" },
    menuButton: {
      display: "flex",
      w: "full",
      alignItems: "center",
      gap: "2",
      overflow: "hidden",
      rounded: "xl",
      px: "3",
      py: "2",
      textAlign: "left",
      fontSize: "sm",
      whiteSpace: "nowrap",
      ringC: "sidebar.ring",
      outline: "none",
      transitionProperty: "width, height, padding",
      transitionDuration: "200ms",
      "[data-slot='sidebar-menu-item']:has([data-sidebar=menu-action]) &": { pr: "8" },
      "[data-slot='sidebar'][data-collapsible=icon] &": { size: "8!", p: "2!" },
      _hover: { bg: "sidebar.accent", color: "sidebar.accent.foreground" },
      _focusVisible: { ringW: "3" },
      _active: { bg: "sidebar.accent", color: "sidebar.accent.foreground" },
      _disabled: { pointerEvents: "none", opacity: "0.5" },
      "&:has(> svg:first-child)": { pl: "2.5" },
      "&:has(> svg:last-child)": { pr: "2.5" },
      "&[aria-disabled='true']": { pointerEvents: "none", opacity: "0.5" },
      "&:where([data-state='open'], [data-open]:not([data-open='false']))": {
        _hover: { bg: "sidebar.accent", color: "sidebar.accent.foreground" },
      },
      "&:where([data-active='true'])": {
        bg: "sidebar.accent",
        fontWeight: "medium",
        color: "sidebar.accent.foreground",
      },
      "& svg": { size: "4", flexShrink: "0" },
      "& > span:last-child": { textOverflow: "ellipsis", overflow: "hidden", whiteSpace: "nowrap" },
    },
    menuAction: {
      position: "absolute",
      top: "1.5",
      right: "1",
      display: "flex",
      aspectRatio: "square",
      w: "5",
      alignItems: "center",
      justifyContent: "center",
      rounded: "xl",
      p: "0",
      color: "sidebar.foreground",
      ringC: "sidebar.ring",
      outline: "none",
      transitionProperty: "transform",
      "[data-slot='sidebar'][data-collapsible=icon] &": { display: "none" },
      "[data-slot='sidebar-menu-button']:hover ~ &": { color: "sidebar.accent.foreground" },
      "[data-slot='sidebar-menu-button'][data-size=default] ~ &": { top: "1.5" },
      "[data-slot='sidebar-menu-button'][data-size=lg] ~ &": { top: "2.5" },
      "[data-slot='sidebar-menu-button'][data-size=sm] ~ &": { top: "1" },
      "&::after": { content: '""', position: "absolute", inset: "-2" },
      _hover: { bg: "sidebar.accent", color: "sidebar.accent.foreground" },
      _focusVisible: { ringW: "3" },
      md: { "&::after": { display: "none" } },
      "& > svg": { size: "4", flexShrink: "0" },
    },
    menuBadge: {
      pointerEvents: "none",
      position: "absolute",
      right: "1",
      display: "flex",
      h: "5",
      minW: "5",
      alignItems: "center",
      justifyContent: "center",
      rounded: "xl",
      px: "1",
      fontSize: "xs",
      fontWeight: "medium",
      color: "sidebar.foreground",
      fontVariantNumeric: "tabular-nums",
      userSelect: "none",
      "[data-slot='sidebar'][data-collapsible=icon] &": { display: "none" },
      "[data-slot='sidebar-menu-button']:hover ~ &": { color: "sidebar.accent.foreground" },
      "[data-slot='sidebar-menu-button'][data-size=default] ~ &": { top: "1.5" },
      "[data-slot='sidebar-menu-button'][data-size=lg] ~ &": { top: "2.5" },
      "[data-slot='sidebar-menu-button'][data-size=sm] ~ &": { top: "1" },
      "[data-slot='sidebar-menu-button']:where([data-active]:not([data-active='false'])) ~ &": {
        color: "sidebar.accent.foreground",
      },
    },
    menuSkeleton: {
      display: "flex",
      h: "8",
      alignItems: "center",
      gap: "2",
      rounded: "xl",
      px: "2",
    },
    menuSkeletonIcon: { size: "4", rounded: "xl" },
    menuSkeletonText: { h: "4", maxW: "var(--skeleton-width)", flex: "1" },
    menuSub: {
      mx: "3.5",
      display: "flex",
      minW: "0",
      transform: "translateX(1px)",
      flexDirection: "column",
      gap: "1",
      borderLeftWidth: "1px",
      borderColor: "sidebar.border",
      px: "2.5",
      py: "0.5",
      "[data-slot='sidebar'][data-collapsible=icon] &": { display: "none" },
    },
    menuSubItem: { position: "relative" },
    menuSubButton: {
      display: "flex",
      h: "7",
      minW: "0",
      transform: "translateX(-1px)",
      alignItems: "center",
      gap: "2",
      overflow: "hidden",
      rounded: "xl",
      px: "3",
      color: "sidebar.foreground",
      ringC: "sidebar.ring",
      outline: "none",
      "[data-slot='sidebar'][data-collapsible=icon] &": { display: "none" },
      _hover: { bg: "sidebar.accent", color: "sidebar.accent.foreground" },
      _focusVisible: { ringW: "3" },
      _active: { bg: "sidebar.accent", color: "sidebar.accent.foreground" },
      _disabled: { pointerEvents: "none", opacity: "0.5" },
      "&[aria-disabled='true']": { pointerEvents: "none", opacity: "0.5" },
      "&[data-size=md]": { fontSize: "sm" },
      "&[data-size=sm]": { fontSize: "xs" },
      "&:where([data-active='true'])": { bg: "sidebar.accent", color: "sidebar.accent.foreground" },
      "& > span:last-child": { textOverflow: "ellipsis", overflow: "hidden", whiteSpace: "nowrap" },
      "& > svg": { size: "4", flexShrink: "0", color: "sidebar.accent.foreground" },
    },
  },
  variants: {
    sidebarVariant: {
      sidebar: {
        gap: {
          "[data-slot='sidebar'][data-collapsible=icon] &": { w: "var(--sidebar-width-icon)" },
        },
        container: {
          "[data-slot='sidebar'][data-collapsible=icon] &": { w: "var(--sidebar-width-icon)" },
          "[data-slot='sidebar'][data-side=left] &": { borderRightWidth: "1px" },
          "[data-slot='sidebar'][data-side=right] &": { borderLeftWidth: "1px" },
        },
      },
      floating: {
        gap: {
          "[data-slot='sidebar'][data-collapsible=icon] &": {
            w: "calc(var(--sidebar-width-icon) + var(--spacing, 0.25rem) * 4)",
          },
        },
        container: {
          p: "2",
          "[data-slot='sidebar'][data-collapsible=icon] &": {
            w: "calc(var(--sidebar-width-icon) + var(--spacing, 0.25rem) * 4 + 2px)",
          },
        },
      },
      inset: {
        gap: {
          "[data-slot='sidebar'][data-collapsible=icon] &": {
            w: "calc(var(--sidebar-width-icon) + var(--spacing, 0.25rem) * 4)",
          },
        },
        container: {
          p: "2",
          "[data-slot='sidebar'][data-collapsible=icon] &": {
            w: "calc(var(--sidebar-width-icon) + var(--spacing, 0.25rem) * 4 + 2px)",
          },
        },
      },
    },
    menuButtonVariant: {
      default: {
        menuButton: { _hover: { bg: "sidebar.accent", color: "sidebar.accent.foreground" } },
      },
      outline: {
        menuButton: {
          bg: "background",
          boxShadow: "0 0 0 1px hsl(var(--sidebar-border))",
          _hover: {
            bg: "sidebar.accent",
            color: "sidebar.accent.foreground",
            boxShadow: "0 0 0 1px hsl(var(--sidebar-accent))",
          },
        },
      },
    },
    menuButtonSize: {
      default: { menuButton: { h: "8", fontSize: "sm" } },
      sm: { menuButton: { h: "7", fontSize: "xs" } },
      lg: {
        menuButton: {
          h: "12",
          px: "3",
          fontSize: "sm",
          "[data-slot='sidebar'][data-collapsible=icon] &": { p: "0!" },
        },
      },
    },
    menuActionShowOnHover: {
      true: {
        menuAction: {
          "[data-slot='sidebar-menu-item']:focus-within &": { opacity: "1" },
          "[data-slot='sidebar-menu-item']:hover &": { opacity: "1" },
          "[data-slot='sidebar-menu-button']:where([data-active]:not([data-active='false'])) ~ &": {
            color: "sidebar.accent.foreground",
          },
          "&[aria-expanded='true']": { opacity: "1" },
          md: { opacity: "0" },
        },
      },
    },
  },
  defaultVariants: {
    sidebarVariant: "sidebar",
    menuButtonVariant: "default",
    menuButtonSize: "default",
    menuActionShowOnHover: false,
  },
});
